# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_ur_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_information',
            name='id',
        ),
        migrations.AddField(
            model_name='user_information',
            name='users_id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
