# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_ur_home', '0002_auto_20171104_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_information',
            old_name='users_id',
            new_name='id',
        ),
    ]
