# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-05 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_ur_home', '0004_auto_20171105_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
