# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_ur_home', '0006_auto_20171106_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_image',
            name='image',
            field=models.ImageField(upload_to='houses_images/'),
        ),
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.ImageField(default='user_img.png', upload_to='users_images/'),
        ),
    ]
