# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_ur_home', '0007_auto_20171106_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house_image',
            name='image',
            field=models.FileField(upload_to='houses_images/'),
        ),
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.FileField(default='user_img.png', upload_to='users_images/'),
        ),
    ]
